export const DEFAULT_VALUE = {
  HEIGHT: 150,
  WIDTH: 800,
  FULL_WIDTH: false,
  COLOR_HUE: 0,
  MULTI_COLOR: false,
  HIDE_FRAME: false,
  COLORED_OFF_LIGHTS: true,
  ANIMATION_FRAMES_PER_UPDATE: 3,
};

export const MAX_CHARACTERS = 1000;

export const MIN_VALUE = {
  HEIGHT: 50,
  WIDTH: 100,
  COLOR_HUE: 0,
  ANIMATION_FRAMES_PER_UPDATE: 1,
};

export const MAX_VALUE = {
  COLOR_HUE: 360,
};
