export const DEFAULT_VALUE = {
  HEIGHT: 200,
  WIDTH: 800,
  FULL_WIDTH: false,
  HUE_DEGREES: 0,
  FRAME_PROPORTION: 0.2,
  ANIMATION_FRAMES_PER_UPDATE: 3,
  ANIMATION_DELAY: 0,
  PARTY_MODE: false,
};

export const MAX_CHARACTERS = 1000;

export const MIN_VALUE = {
  HEIGHT: 50,
  WIDTH: 100,
  HUE_DEGREES: 0,
  FRAME_PROPORTION: 0,
  ANIMATION_FRAMES_PER_UPDATE: 1,
  ANIMATION_DELAY: 0,
};

export const MAX_VALUE = {
  HUE_DEGREES: 360,
  FRAME_PROPORTION: 0.5,
};
