import { COLOR_VALUES } from "./colors";

export const DEFAULT_VALUE = {
  HEIGHT: 150,
  WIDTH: 800,
  FULL_WIDTH: false,
  COLOR_HUE: COLOR_VALUES.LIGHT.hue,
  ON_BULB_LIGHTNESS: COLOR_VALUES.BULB_ON.lightness,
  OFF_BULB_LIGHTNESS: COLOR_VALUES.BULB_OFF.lightness,
  FRAME_LIGHTNESS: COLOR_VALUES.FRAME.lightness,
  BACKGROUND_LIGHTNESS: COLOR_VALUES.BACKGROUND.lightness,
  HIDE_FRAME: false,
  COLORED_OFF_LIGHTS: true,
  ANIMATION_FRAMES_PER_UPDATE: 6,
};

export const MAX_CHARACTERS = 100;

export const MIN_VALUE = {
  HEIGHT: 60,
  WIDTH: 100,
  COLOR_HUE: 0,
  ON_BULB_LIGHTNESS: 70,
  OFF_BULB_LIGHTNESS: 0,
  FRAME_LIGHTNESS: 10,
  BACKGROUND_LIGHTNESS: 0,
  ANIMATION_FRAMES_PER_UPDATE: 1,
};

export const MAX_VALUE = {
  COLOR_HUE: 360,
  ON_BULB_LIGHTNESS: 100,
  OFF_BULB_LIGHTNESS: 30,
  FRAME_LIGHTNESS: 40,
  BACKGROUND_LIGHTNESS: 30,
  ANIMATION_FRAMES_PER_UPDATE: 60,
};
